version: '3'
services:
  wordpress:
    container_name: wp-web
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "$PWD/html:/var/www/html"
    ports:
      - "8080:80"
    networks:
      - my_net
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
  db:
    container_name: wp-mysql
    image: mysql:5.7
    volumes:
      - $PWD/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    ports:
      - "33060:3306"
    networks:
      - my_net
networks:
  my_net: